// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jktztyyjulpxoyhoagvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprdHp0eXlqdWxweG95aG9hZ3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NzE1NDQsImV4cCI6MjA1MzE0NzU0NH0.ALX8dNBakB4NWAkcpJ_OfzV3w0mYW81r6luA3s0OD48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);